version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    restart: unless-stopped
  kafka:
    image: wurstmeister/kafka:2.13-2.6.3
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /tmp/kafka-data/data:/data
      - /tmp/kafka-data/logs:/logs
      - ../certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
